### ISSUE TITLE
Cannot resolve . Please help

### ISSUE THREAD

**Issue by estherRGU** [laurie71/node-api#1]
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/app/npm-debug.log

**Comment by laurie71** [comment]
Hi estherRGU, and thanks for checking this project out. Note, however, that it's 6 years old! It was something I developed experimentally when I first started using Node. That said, I'd be happy to help get this working for you, but I'd need more information than you provided to do that.

Can you attach the npm-debug.log to this issue? Or provide some details of what went wrong? What was the `npm install` command you entered, and what was the full output of that command? What operating system were you using, and with what version of Node?

Regards,

Laurie

**Comment by estherRGU** [comment]
Hello Laurie,
Thanks for your response. Below is the error log I receive when I tested my JSON package file.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose config Skipping project config: C:\Users\ESTHER/.npmrc. (matches userconfig)
5 verbose stack Error: missing script: start
5 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:142:19)
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:58:5
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
5 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
5 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
5 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
5 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:295:20)
5 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
5 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete](fs.js:303:13)
6 verbose cwd C:\Users\ESTHER
7 error Windows_NT 10.0.10586
8 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
9 error node v4.4.7
10 error npm  v2.15.8
11 error missing script: start
12 error If you need help, you may report this error at:
12 error     https://github.com/npm/npm/issues
13 verbose exit [ 1, true ]

**Comment by laurie71** [comment]
It appears from that npm log that you tried to run `npm start` from within a package that has no start script specified in its package.json. See, for example, line 11 of your output:

```
11 error missing script: start
```

That doesn't seem to be related to the error you posted initially. I can also see you're using Node version 4.4.7. Note again that this is a very old package, originally written against Node 0.4. That said, I just tried it with Node 5.x and it seems to still work, so you still need to detail how you produced the error you're encountering for me to be able to help.
